version: '3.1'
services:
  firebase:
    container_name: octo_firebase
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    image: voraciousdev/firebase-tools
    ports:
      - 4400:4400
      - 4500:4500
      - 32775:32775
      - 32776:32776
      - 32777:32777
      - 32778:32778
    stdin_open: true
    tty: true
    volumes:
      - ./firebase:/firebase/volume
