name: ci
on:
  pull_request:
  push:
    branches:
      - main
env:
  CYPRESS_BASE_URL: http://localhost:8889
  FIREBASE_PROJECT_ID: demo-octo
  NUXT_PUBLIC_CDN_URL:
  NUXT_PUBLIC_DISCORD_INVITE_LINK:
  NUXT_PUBLIC_FATHOM_EVENT_ACCOUNT_REGISTRATION:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_CONTINUE_WITH_PRO:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_MODAL_UPGRADE:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_OPEN_APP:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_SAVE_DOCS:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_SETTINGS_UPGRADE:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_SIGN_UP_NOW:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_TRY_IT_OUT:
  NUXT_PUBLIC_FATHOM_EVENT_CTA_UPGRADE_TO_PRO:
  NUXT_PUBLIC_FATHOM_SITE_ID:
  NUXT_PUBLIC_FATHOM_SITE_URL:
  NUXT_PUBLIC_FIREBASE_API_KEY: fake
  NUXT_PUBLIC_FIREBASE_APP_ID: fake
  NUXT_PUBLIC_FIREBASE_AUTH_DOMAIN: fake
  NUXT_PUBLIC_FIREBASE_DATABASE_URL: fake
  NUXT_PUBLIC_FIREBASE_EMULATOR_AUTH: http://localhost:32775
  NUXT_PUBLIC_FIREBASE_EMULATOR_BYPASS:
  NUXT_PUBLIC_FIREBASE_EMULATOR_FIRESTORE_HOST: localhost
  NUXT_PUBLIC_FIREBASE_EMULATOR_FIRESTORE_PORT: 32776
  NUXT_PUBLIC_FIREBASE_EMULATOR_FUNCTIONS_HOST: localhost
  NUXT_PUBLIC_FIREBASE_EMULATOR_FUNCTIONS_PORT: 32779
  NUXT_PUBLIC_FIREBASE_EMULATOR_STORAGE_HOST: localhost
  NUXT_PUBLIC_FIREBASE_EMULATOR_STORAGE_PORT: 32778
  NUXT_PUBLIC_FIREBASE_LOG_LEVEL:
  NUXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: fake
  NUXT_PUBLIC_FIREBASE_PROJECT_ID: demo-octo
  NUXT_PUBLIC_FIREBASE_STORAGE_BUCKET: fake
  NUXT_PUBLIC_STRIPE_MONTHLY_PRICE:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build
  test-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v4.2.2
        with:
          config: baseUrl=http://localhost:8889
          build: yarn build
          start: yarn preview:latest
          wait-on: http://localhost:32777
  test-cypress-nuxt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v4.2.2
        with:
          config: baseUrl=http://localhost:3000
          build: yarn nuxt:build
          start: yarn nuxt:preview
          wait-on: http://localhost:32777
